### ISSUE TITLE
`AfterClaim` must be defined only once in the type namespace of this module

### ISSUE THREAD

**Issue by Eh1Ka6** [near-examples/crossword-tutorial-chapter-3#2]
Trying to run  this  example with rustc 1.61

Don't know if i'm misssing something but using the trait twice fails with : 
`AfterClaim` must be defined only once in the type namespace of this module

When removing afterclaim the call to the ext_self fails with:  
cannot find function in module ext_self

**Comment by bucanero** [comment]
This example has been updated to the latest NEAR SDK 5.1.0 (PR #5 )

Try building now with `cargo near build`, it should work fine.
